Develop
FIT-2024-RecALL/recall-back pull request #11
Opened 2024-10-17 04:33 UTC by AntonTsoy

2024-10-18 11:48 UTC, KozlovKV requested changes
Писал комменты, основываясь на своих небольших и не самых новых знаниях бэкэнда, так что возможно что-то мега-глупое и неактуальное. Заранее сорри

2024-10-18 11:48 UTC, KozlovKV commented on app/routers/users.py
> +@router.post("/{user_id}/collections/", response_model=schemas.collection.Collection, tags=["collection"])
В этой ветке будто бы не будет смысла, т.к. только авторизованный пользователь может создавать коллекции, а значит обработчик POST-запроса на `/collections` уже будет привязывать коллекцию к пользователю

2024-10-18 11:48 UTC, KozlovKV commented on app/routers/train_records.py
> +@router.post("/{card_id}/{user_id}", response_model=schemas.train_record.TrainRecord)
Здесь по той же причине не надо указывать `user_id`

2024-10-18 11:48 UTC, KozlovKV commented on app/routers/collections.py
> +
В этом наборе роутов наверное хотелось бы ещё иметь GET `/{collection_id}/cards` для получения карточек, связанных с этой коллекцией и GET `/{collection_id}/cards/train_records` для получения тренировочных записей по карточкам, добавленным к этой коллекции

2024-10-18 11:48 UTC, KozlovKV commented on app/routers/users.py
> +
Здесь ещё было бы классно добавить путь `/profile`, который будет возвращать данные текущего авторизованного пользователя

2024-10-18 11:48 UTC, KozlovKV commented on app/main.py
> +@app.put("/root/{card_id}/{collection_id}", tags=["root"])
А! Вот где этот PUT-запрос. Его разделить было бы классно на POST для создания связи и DELETE для её удаления. Ну и вместо `/root` другой префикс можно. Как вариант, сделать `/collections/{collection_id}/pair/{card_id}` для POST и `/collections/{collection_id}/unpair/{card_id}` для DELETE

2024-10-18 11:48 UTC, KozlovKV commented on app/models.py
> +    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
Тут не запрос изменений, а скорее любопытство - можно ли указывать, к чему отсылается поле не строкой, а типом схемы? То есть написать вместо `"users.id"` что-то вроде `User.id`?

2024-10-18 11:48 UTC, KozlovKV commented on app/models.py
> +    cards: Mapped[list["Card"]] = relationship(
Тут наверное скобок быть не должно?

2024-10-18 13:34 UTC, AntonTsoy commented on app/models.py
> +    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
Можно, особенно в данном случае. Но когда моделей становится много, их соответственно разносят по отдельным файлам. Если сослаться на другую таблицу через `User.id`, то придется импортировать класс таблицы из другого модуля. А возможно в тот модуль уже импортирован наш текущий модуль. Так мы получаем циклическое импортирование и Exception

2024-10-18 13:39 UTC, AntonTsoy commented on app/models.py
> +    cards: Mapped[list["Card"]] = relationship(
Если ты про кавычки, то строковый тип тут используется, потому что Cards и Collections ссылаются друг на друга. Один из них должен быть объявлен раньше другого, поэтому возникает проблема, что для первого объявленного в коде не объявлен ещё второй (используется несуществующий класс), получаем Exception

2024-10-18 14:36 UTC, AntonTsoy commented on app/models.py
> +    cards: Mapped[list["Card"]] = relationship(
Параметр `back_populates` может принимать только либо строку, либо `None`. Кстати, я про этот параметр отдельно писал в Wiki

2024-10-18 14:43 UTC, AntonTsoy commented on app/models.py
> +    train_records: Mapped[list[TrainRecord]] = relationship("TrainRecord")
https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship

2024-10-18 14:52 UTC, AntonTsoy commented on app/models.py
> +    collections: Mapped[list[Collection]] = relationship("Collection")
Строка нужна, чтобы избежать 1) циклических импортов; 2) NameError: мы можем ссылаться на класс, который будет объявлен в коде ниже.

Вообще так, как мы переходим с ORM на Core, то мы больше не будем использовать функцию `relationship`. Мало смысла в том, чтобы обсуждать детали, с ней связанные. Пусть тут останется артефакт в виде ссылки на официальную документацию.

https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship

2024-10-18 14:55 UTC, AntonTsoy commented on app/routers/users.py
> +
Это ты на будущее? Просто как мне сейчас возвращать текущего авторизованного пользователя, если у нас нет авторизации?

2024-10-18 16:12 UTC, KozlovKV commented on app/routers/users.py
> +
Ну да, в первую очередь на будущее. А можно заглушку и сейчас написать

2024-10-18 16:12 UTC, KozlovKV commented on app/models.py
> +    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
Аргумент. Ну, собственно, оно ведь просто упадёт при запуске, если там будет указано несуществующее значение?

2024-10-18 16:17 UTC, KozlovKV commented on app/models.py
> +class Card(Base):
А, да? Ну... Тут вопрос во многом от реализации зависит. Если у нас будет роут PUT `/cards/{card_id}/` для обновления, то... То мы также сможем и коллекцию получить в целом. Но тогда вопрос: сильно ли будет затратно по ресурсам получать из БД дополнительно ещё и коллекцию?

2024-10-18 16:20 UTC, KozlovKV commented on app/models.py
> +    cards: Mapped[list["Card"]] = relationship(
Ой, сорри. К этой конструкции у меня вопросов не было. Они возникли к `relationship(str)`

2024-10-18 16:21 UTC, KozlovKV commented on app/models.py
> +    collections: Mapped[list[Collection]] = relationship("Collection")
А в core как будут связи работать?

2024-10-18 16:37 UTC, AntonTsoy commented on app/models.py
> +class Card(Base):
+ 1 SELECT запрос

2024-10-19 12:51 UTC, AntonTsoy commented on app/routers/train_records.py
> +@router.post("/{card_id}/{user_id}", response_model=schemas.train_record.TrainRecord)
Оставим это до момента, когда будет сделана авторизация

2024-10-19 12:54 UTC, AntonTsoy commented on app/routers/collections.py
> +
Первое эндпоинт сделал, второй хотелось бы завершить, когда уже полностью перейдем на Core стиль. Если делать его прямо сейчас то, там очень некрасивый и костыльный код получается

2024-10-19 13:00 UTC, AntonTsoy commented on app/routers/users.py
> +@router.post("/{user_id}/collections/", response_model=schemas.collection.Collection, tags=["collection"])
Ждем авторизацию. А пока я могу колоду привязать к пользователю только так. Но я внес небольшие изменения. Из эндпоинта POST `/users/{user_id}/collections` он превратился в POST `/collections/{user_id}`

2024-10-19 13:13 UTC, AntonTsoy commented on app/routers/users.py
> +
Сделал заглушку

2024-10-19 13:25 UTC, AntonTsoy commented on app/models.py
> +    password: Mapped[str] = mapped_column(String(100))
Надеюсь 1024 хватит

2024-10-21 06:01 UTC, KozlovKV commented on app/routers/collections.py
> +    if check_connections(collection_id, cards, db):
Правильно ли я понял, что мы не свяжем карточки, если хотя бы одна уже привязана?

2024-10-21 06:05 UTC, KozlovKV commented on app/models.py
> +class Card(Base):
Ладно, можно будет это проблему решить позже

2024-10-21 06:06 UTC, KozlovKV commented on app/main.py
> +@app.get("/profile", response_model=schemas.user.User, tags=["profile"])
Я думал, это будет в ветке `/users`, но ладно

2024-10-21 06:07 UTC, AntonTsoy commented on app/routers/collections.py
> +    if check_connections(collection_id, cards, db):
Абсолютно верно

2024-10-21 06:09 UTC, AntonTsoy commented on app/main.py
> +@app.get("/profile", response_model=schemas.user.User, tags=["profile"])
Не помню, почему сделал так. Может потому что это просто временное решение

2024-10-21 06:12 UTC, merged

2024-10-21 06:13 UTC, KozlovKV commented on app/routers/collections.py
> +
А в чём особенная некрасивость? Большая вложенность селектов?

2024-10-21 06:14 UTC, AntonTsoy commented
> Авторизация начинает напрашиваться всё больше. Надо будет скоро к ней приступить. Если хочешь, могу я заняться изучением этого вопроса

Как только закончу с Core, сразу займусь этим вопросом