Fix Authentication
FIT-2024-RecALL/recall-back pull request #28
Opened 2024-11-09 15:44 UTC by AntonTsoy

2024-11-09 20:27 UTC, KozlovKV requested changes

2024-11-09 20:27 UTC, KozlovKV commented on app/auth/utils.py
>      auth_data: dict = authSettings.get_auth_data
А сейчас у меня возник вопрос, зачем вообще нужно это property, возвращающее словарь из полей класса, ведь дальше ты передаёшь эти поля по отдельности?

2024-11-09 20:27 UTC, KozlovKV commented on app/routers/cards.py
> +        user_id: int = await crud.user.get_profile_id(conn, token)
Во всех местах, где требуется авторизация, мы будем извлекать из токена id пользователя. Может быть тогда добавить в dependencies такой вариант напрямую, а в функции роута сразу в качестве аргумента получать current_user_id?

2024-11-09 20:27 UTC, KozlovKV commented on app/crud/user.py
> +async def get_profile_id(conn: AsyncConnection, token: str) -> int:
Эту штуку будто бы можно перенести в auth/utils или какой-то ещё файлик в той папке, ведь тут у нас никакого взаимодействия с БД нет

2024-11-09 20:27 UTC, KozlovKV commented on app/routers/users.py
> +    return {"message": "User logged out"}
Тут также код 200 можно просто кидать

2024-11-09 20:27 UTC, KozlovKV commented on app/routers/users.py
>      return {"access_token": access_token, "refresh_token": None}
Могу ошибаться, но по идее возвращать так токен опасно и даже не нужно. Можно также удачным кодом ограничиться

2024-11-09 20:29 UTC, KozlovKV commented on compose.yaml
>    postgres:
Посмотри мой ПР 👉👈🥺

2024-11-21 04:20 UTC, BenBenNotGood reviewed
В целом вижу, что методы создания/проверки токена сделаны, но далеко не везде проверяются. Также не везде следишь за типизацией функций, а конкретно за возвращаемыми значениями.

2024-11-21 04:20 UTC, BenBenNotGood commented on app/routers/cards.py
> +async def delete_card(conn: DBConnection, card_id: int):
issue: А тут что токен не проверяется?

2024-11-21 04:20 UTC, BenBenNotGood commented on app/routers/cards.py
> +async def create_card(conn: DBConnection, token: JWToken, card: CardCreate):
suggestion (blocking): Смотри, у тебя ручка обрабатывает конкретный бизнес-кейс, но использует JWToken зависимость, что для этой бизнес-ручки слишком низкоуровнево.
Почему бы не завести зависимость сразу с выдачей пользователя, совершающего действие.

2024-11-21 04:20 UTC, BenBenNotGood commented on app/routers/train_records.py
> +async def read_user_card_last_train_record(conn: DBConnection, token: JWToken, card_id: int):
question: Вот этот и верхний метод друг друга напоминают.
Может их как-то объединить с гибкой фильтрацией?

2024-11-21 04:20 UTC, BenBenNotGood commented on app/routers/cards.py
> +    await crud.train_record.delete_train_record_by_card(conn, card_id)
thought: Тут неплохо бы подумать вот о чем.
Удаление происходит за три метода.
1. Если бы между таблицами был бы установлен foreign key on delete cascade, то удаление можно было бы сделать за один метод.
2. Но возможно первый вариант слишком радикальный, и мы не хотим физически удалять ни карточку, ни историю тренировок. То есть возможно стоит сделать soft delete.

2024-11-25 13:43 UTC, AntonTsoy commented on app/auth/utils.py
> +    token_data = {"sub": str(user_id), "exp": expire}
Я пытался, так делать, но получал ошибку при декодировании токена. Сейчас погуглил на эту тему, оказалось, что поле "sub" по RFC должно быть строкой
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2

2024-11-26 05:12 UTC, KozlovKV reviewed
Добавил в auth.env несколько полей, которые будут определять параметры устанавливаемых куков. Для большинства из них есть параметры по умолчанию. Надо прописать обязательно только `ACCESS_TOKEN_KEY=<key>`

2024-11-26 05:12 UTC, KozlovKV commented on app/config.py
> +    def cookie_kwargs(self) -> dict:
Я хз, как этот тип красиво прописать, но надо будет...

@AntonTsoy , мы ведь можем тут указать класс, отнаследованный от BaseModel?

2024-11-26 06:01 UTC, AntonTsoy commented on app/config.py
> +    def cookie_kwargs(self) -> dict:
готово

2024-11-27 04:30 UTC, AntonTsoy commented on app/crud/card_collection.py
>      new_connections: list[int] = [x for x in cards if x not in exist_connections]
Можно использовать множества. Но в силу того, что теперь фронтенд немного по-другому устанавливает связь между карточками и коллекциями, этот код надо сильно поменять

2024-11-28 15:46 UTC, merged