Refactor for front
FIT-2024-RecALL/recall-back pull request #35
Opened 2024-12-05 08:57 UTC by KozlovKV

2024-12-07 16:06 UTC, KozlovKV commented
Произошла так называемая ~проёбка~ ошибка планирования, поэтому для удобства фронта сделал кое-какие из запросов для списков коллекций возвращающими не только IDшники, но и не объекты целиком (без описания)

2024-12-12 03:57 UTC, BenBenNotGood commented on app/routers/storage.py
> +        await crud.check_user_id(conn, user_id)
Нет ощущения, что вот этот паттерн с проверкой пользователя и выбросом исключения можно было бы сделать один раз, скажем, где-нибудь в FastAPI dependencies?

2024-12-12 03:57 UTC, BenBenNotGood commented on app/crud/card.py
> +    return [card['id'] for card in result.mappings().all()]
`list(result.scalars().all()`

2024-12-12 07:54 UTC, KozlovKV commented on app/routers/storage.py
> +        await crud.check_user_id(conn, user_id)
Да. Где-то уже об этом сам писал. Чуть позже этим займётся Антон во время большого рефактора

2024-12-12 16:34 UTC, AntonTsoy requested changes

2024-12-12 16:34 UTC, AntonTsoy commented on app/crud/storage.py
> +    # TODO: Here can be some additional extension's checks
> Here can be some additional extension's checks

Ага, ну либо просто импорт стандартной библиотеки `os`. Смотри пример кода: https://github.com/FIT-2024-Digital-Library/digital-library-back/blob/main/app/routes/storage.py

2024-12-12 16:34 UTC, AntonTsoy commented on app/crud/card_collection.py
> +    return list(result.scalars().all())
**Comment**

Забавно. Мне пришлось дополнительно написать эту функцию, пока делал тренировки. В общем мне хотелось бы взять на себя обязанность решать merge conflict. Надо использовать мою реализацию, там более просто запрос к БД.

2024-12-12 16:34 UTC, AntonTsoy commented on app/routers/collections.py
>  async def read_collections(conn: DBConnection, limit: int = 100, skip: int = 0) -> list[Collection]:
ого, оказывается можно функциям одинаковые имена давать

2024-12-12 18:07 UTC, KozlovKV commented on app/routers/collections.py
>  async def read_collections(conn: DBConnection, limit: int = 100, skip: int = 0) -> list[Collection]:
Сам в шоке

2024-12-12 18:07 UTC, KozlovKV commented on app/crud/card_collection.py
> +    return list(result.scalars().all())
As you want

2024-12-12 18:08 UTC, KozlovKV commented on app/crud/storage.py
> +    # TODO: Here can be some additional extension's checks
Тут речь шла о проверках на то, что это расширение от аудио/видео/фото

А функция классная

2024-12-13 05:32 UTC, AntonTsoy commented on app/crud/card_collection.py
> +    return list(result.scalars().all())
> (я не то чтобы сильно вдумывался в запросы, просто менял возвращаемые типы)

Я понимаю, перед тобой стояли другие задачи

2024-12-13 05:40 UTC, AntonTsoy commented on app/routers/collections.py
>  async def read_collections(conn: DBConnection, limit: int = 100, skip: int = 0) -> list[Collection]:
смотри сам

2024-12-14 10:04 UTC, AntonTsoy approved these changes

2024-12-14 10:04 UTC, merged